### ISSUE TITLE
Expand and improve details in README

### ISSUE THREAD

**Issue by cjstyles6** [Adassa-Enterprise-Solutions/adassa-store#19]
### The current README provides a brief overview of the project, but is missing important information to orient new users and contributors.

**I'd be glad to take on the task of reworking the README content and structure. Please assign me to this issue so I can submit a more comprehensive README.**

**Comment by desbenn** [comment]
Thanks for reaching out but I don't need the README to reworked at this time.

**Comment by cjstyles6** [comment]
Sure
